version: '3'
services:
  emqx:
    build: .
    networks:
      - test-network
    environment:
      - MQTT_PORT=1883
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=dns
      - EMQX_CLUSTER__DNS__NAME=emqx
      - EMQX_CLUSTER__DNS__RECORD_TYPE=a
    labels:
      - traefik.enable=true
      - traefik.tcp.services.emqx.loadbalancer.server.port=1883
      - traefik.tcp.routers.emqx.entrypoints=emqx
      - traefik.tcp.routers.emqx.rule=HostSNI(`*`)
      - traefik.tcp.routers.emqx.service=emqx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:18083/health"]
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 4
      restart_policy:
        condition: any

  emqx-auth-provider:
    build: 
      context: .
      dockerfile: Dockerfile.auth
    networks:
      - test-network
    environment:
      # Vars used by the authentication server
      - EMQX_USERNAME=backend
      - EMQX_PASSWORD=nWK8Am3d2Hbupx
    labels:
      - traefik.enable=true
      - traefik.tcp.services.emqxauth.loadbalancer.server.port=31337
      - traefik.tcp.routers.emqxauth.entrypoints=emqxauth
      - traefik.tcp.routers.emqxauth.rule=HostSNI(`*`)
      - traefik.tcp.routers.emqxauth.service=emqxauth
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: any
    
  traefik:
    image: traefik:v2.9
    hostname: traefik
    networks:
      - test-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports: 
      - "1883:1883"
      - "8080:8080"
      - "31337:31337"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=test-network
      - --entryPoints.emqx.address=:1883
      - --entryPoints.emqxauth.address=:31337
      # Enable dashboard
      - --api.insecure=true
      - --log.level=DEBUG

networks:
  test-network:
    name: test-network