version: '3'
services:
  emqx:
    build: mqtt
    networks:
      - test-network
    environment:
      - MQTT_PORT=1883
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=dns
      - EMQX_CLUSTER__DNS__NAME=emqx
      - EMQX_CLUSTER__DNS__RECORD_TYPE=a
      - EMQX_AUTHENTICATION__1__URL=http://emqx-authenticator:8000/
    labels:
      - traefik.enable=true
      - traefik.tcp.services.emqx.loadbalancer.server.port=1883
      - traefik.tcp.routers.emqx.entrypoints=emqx
      - traefik.tcp.routers.emqx.rule=HostSNI(`*`)
      - traefik.tcp.routers.emqx.service=emqx
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 2
      restart_policy:
        condition: any

  emqx-authenticator:
    build: authenticator
    networks:
      - test-network
    environment:
      # Vars used by the authentication server
      - PORT=:8000
      - USERNAMES=backend,user
      - PASSWORDS=nWK8Am3d2Hbupx,mqtt@priobike-2022
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 1
      restart_policy:
        condition: any
    
  traefik:
    image: traefik:v2.9
    hostname: traefik
    networks:
      - test-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports: 
      - "1883:1883"
      - "8080:8080"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=test-network
      - --entryPoints.emqx.address=:1883
      # Enable dashboard
      - --api.insecure=true
      - --log.level=DEBUG

networks:
  test-network:
    name: test-network